### PR TITLE
Matches with andino_gazebo package renaming.

### PR DESCRIPTION
**Pull request by francocipollone**
# 🦟 Bug fix

Related to https://github.com/Ekumen-OS/andino/pull/153 https://github.com/Ekumen-OS/andino/issues/152

## Summary
 - Matches with change in `andino_gazebo` package.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

### CODE REVIEW

**Comment by francocipollone** [comment]
:exclamation:  DO NOT MERGE YET!

1. https://github.com/Ekumen-OS/andino/pull/153 should be merged
2. CI here should be retriggered
3. Merge this PR.

**Comment by francocipollone** [comment]
Retriggering jobs as upstream PR is already merged.

**Review by Voldivh — APPROVED** [review]
LGTM

**Comment by francocipollone** [comment]
CI failed: https://github.com/Ekumen-OS/andino_integration_tests/actions/runs/6326397103/job/17191661963?pr=23
Trying to understand what I broke

**Pull request merged**
